language: ruby
sudo: false
rvm:
  - 2.2.6
  - 2.3.3
script:
  - cd spec/dummy && RAILS_ENV=test bundle exec rake db:create db:migrate
  - cd ../.. && bundle exec rspec spec
addons:
  chrome: stable
install:
  - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
deploy:
  provider: rubygems
  api_key:
    secure: PEMMDcT4SKPdv4xMJmIEpndOGePsV3kDOhUL0vEDjTeyxBrn+iBgHKF9itSYbUmOSTuOaiIVleYmuC6GoAmg4KcZIZvfCA61cGCX1ADU5nwh5FjC/tAEs8eShMR3RFG6wyykb4MdFkE2jVpm/W0pyciLgW2HrM6iYzI6X2iMn9E=
  gem: activeadmin_addons
  on:
    tags: true
    repo: platanus/activeadmin_addons
